POST http://localhost:3232/empregados
Content-type: application/json

{
    "nome": "Victor bolinha",
    "idade": 21,
    "cargo": "Analista de Segurançaa"
}


###

GET http://localhost:3232/empregados?search=


###

PUT http://localhost:3232/empregados/
Content-type: application/json

{
    "nome": " ",
    "idade": " ",
    "cargo": " "
}

###


DELETE http://localhost:3232/empregados/